### ISSUE TITLE
Extension doesn't show up

### ISSUE THREAD

**Issue by ghost** [Rutzmoser/inkscape_dimensioning#6]
Hello,

I installed the two files dimensioning.inx and dimensioning.py in the folder C:\Users\.....\AppData\Roaming\inkscape\extensions .
After a restart of Inkscape it doesn't show up in the extensions menu.
I'm using Inkscape 0.92.3 (2405546, 2018-03-11) on Windows 10.
I really would like to use this tool because it is to the point.

Regards Sascha

**Comment by Rutzmoser** [comment]
Do you find the extension in *Extensions -> Create from Path -> Dimensioning*?
