### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by charliebravoAT** [Rutzmoser/inkscape_dimensioning#8]
Hi,

first thanks for the tool.
If I try to use the tool, I get follwoing Error message:
dimensioning.py:47: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--orientation",
dimensioning.py:51: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--arrow_orientation",
dimensioning.py:55: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--line_scale",
dimensioning.py:59: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--overlap",
dimensioning.py:63: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--distance",
dimensioning.py:67: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--position",
dimensioning.py:71: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--flip",
dimensioning.py:75: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--scale_factor",
dimensioning.py:79: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--unit",
dimensioning.py:83: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--rotate",
dimensioning.py:87: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--digit",
dimensioning.py:91: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--tab",
dimensioning.py:327: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  a.affect()
dimensioning.py:118: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  self.helpline_attribs = {'style' : simplestyle.formatStyle(self.helpline_style),
dimensioning.py:122: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  self.text_attribs = {'style'     : simplestyle.formatStyle(self.text_style),
dimensioning.py:126: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  self.dimline_attribs = {'style'  : simplestyle.formatStyle(self.dimline_style),
dimensioning.py:178: DeprecationWarning: Effect.current_layer is now a method in the svg. Use `self.svg.get_current_layer()` instead.
  layer = self.current_layer
dimensioning.py:182: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
  self.grp = inkex.etree.SubElement(layer, 'g', grp_attributes)
dimensioning.py:188: DeprecationWarning: Effect.selected is now a dict in the svg. Use `self.svg.selected`.
  for id, node in self.selected.iteritems():
Traceback (most recent call last):
  File "dimensioning.py", line 327, in <module>
    a.affect()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\deprecated.py", line 180, in affect
    return self.run(args=args)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 123, in run
    self.save_raw(self.effect())
  File "dimensioning.py", line 141, in effect
    self.getPoints()
  File "dimensioning.py", line 188, in getPoints
    for id, node in self.selected.iteritems():
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'

Do you have any idea how to fix it?
InkScape Version is 1.0 (1.0 (4035a4fb49, 2020-05-01)

**Comment by Rutzmoser** [comment]
This seems to be associated with Inkscape 1.0; It should be fixed now.
